### ISSUE TITLE
setsockopt(..., SO_OOBINLINE) is called on eventfds

### ISSUE THREAD

**Issue by MrAnno** [buytenh/ivykis#18]
Hi,

During the investigation of balabit/syslog-ng#1292, we've found something interesting:

https://github.com/buytenh/ivykis/blob/8f8eb788f96ed3a128d240370f1c6afd3c5d1748/src/iv_event_raw_posix.c#L88-L92

https://github.com/buytenh/ivykis/blob/8f8eb788f96ed3a128d240370f1c6afd3c5d1748/src/iv_fd.c#L342

The `iv_fd_*` API is used for `iv_event` as well, and it seems `iv_fd_register()` sets `SO_OOBINLINE` unconditionally, causing a `ENOTSOCK` error in case of eventfds.

```
setsockopt(5, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
setsockopt(6, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
setsockopt(7, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
setsockopt(8, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
setsockopt(9, SOL_SOCKET, SO_OOBINLINE, [1], 4) = -1 ENOTSOCK (Socket operation on non-socket)
```

~I'm not sure about the performance impact, but events are heavily used in syslog-ng, so I think it's worth mentioning.~
Edit: My previous note is invalid, registering events is not a frequent operation, it doesn't really matter from the performance point of view.

@muahao, @bazsi, @furiel

**Comment by buytenh** [comment]
Hello!

Thank you for the report.

Setting `SO_OOBINLINE` is done unconditionally for every file descriptor because there is no `POLLPRI` handling, and anyway, people generally forget to handle `POLLPRI` and to use `recv(..., MSG_OOB)`, which (if I understand the socket API correctly) is a DoS vector.  I'll be happy to debate about whether or not ivykis should be doing this by default.

(If we do think that ivykis should be doing it by default, then I don't think there is a good alternative way to find out whether it is possible to set `SO_OOBINLINE` on a file descriptor to actually just trying it.)

**Comment by MrAnno** [comment]
Hi,

>  I don't think there is a good alternative way to find out whether it is possible to set `SO_OOBINLINE`.

Right. After I realized it didn't affect performance, I should have closed the issue.

Thank you for the explanation. I didn't know about the DoS factor.
